#!/usr/bin/env python3
"""
Process raw Gaia DR3 150-light-year dataset into a classified 3D astronomical star catalog.

Input:  data/gaia_150ly_v2.csv if present, else data/gaia_150ly_v1.csv (see INPUT_FILE)
Names:  data/star_names_simbad.csv (generated by scripts/resolve_star_names.py)
Output: data/star_catalog_150ly_v2.csv from v2 input (star_catalog_150ly_v1.csv from v1 input)
"""

import csv
import os
import re
from pathlib import Path
import pandas as pd

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
from star_classes import classify  # noqa: E402
import numpy as np

# Resolve directories
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Input dataset: 150 ly is the only dataset. Prefer v2 (GCNS-cleaned) when it exists.
INPUT_FILE = (
    DATA_DIR / "gaia_150ly_v2.csv"
    if (DATA_DIR / "gaia_150ly_v2.csv").exists()
    else DATA_DIR / "gaia_150ly_v1.csv"
)
OUTPUT_FILE = DATA_DIR / INPUT_FILE.name.replace("gaia_", "star_catalog_")
NAMES_FILE = DATA_DIR / "star_names_simbad.csv"

input_file = INPUT_FILE
output_file = OUTPUT_FILE

if not input_file.exists():
    raise FileNotFoundError(f"Could not find {input_file.name} in {DATA_DIR}!")


def load_star_names(path=NAMES_FILE):
    """Load SIMBAD-resolved landmark names.

    Returns (gaia_names, hip_names):
      gaia_names: {Gaia DR3 source_id (int): display_name}
      hip_names:  {HIP number (str): display_name}, for Hipparcos-only rows that
                  have no Gaia DR3 ID (alf Cen A/B, Menkent, Dubhe). Keys include
                  the exact SIMBAD value (e.g. "65378A") and the bare number with
                  the component letter stripped ("65378"); for a stripped key
                  shared by several components the first row (the A component)
                  wins. Use it to label Hipparcos-sourced rows by HIP number.
    Raises ValueError if a Gaia DR3 ID appears more than once.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found - run scripts/resolve_star_names.py first."
        )
    gaia_names, hip_names = {}, {}
    with path.open(newline="") as f:
        for row in csv.DictReader(f):
            name = row["display_name"].strip()
            gaia = row["gaia_dr3_source_id"].strip()
            hip = row["hip"].strip()
            if gaia:
                gid = int(gaia)
                if gid in gaia_names:
                    raise ValueError(
                        f"Duplicate Gaia DR3 ID {gid} in {path.name}: "
                        f"{gaia_names[gid]!r} and {name!r}"
                    )
                gaia_names[gid] = name
            if hip:
                hip_names.setdefault(hip, name)
                hip_names.setdefault(re.sub(r"[A-Za-z]+$", "", hip), name)
    return gaia_names, hip_names


print("=" * 70)
print("GAIA DR3 3D STAR CATALOG BUILDER")
print(f"Reading: {input_file}")
print(f"Writing: {output_file}")
print("=" * 70)

df = pd.read_csv(input_file)
print(f"Loaded {len(df):,} stellar sources.")

# Ensure distance columns exist
if "distance_pc" not in df.columns:
    df["distance_pc"] = 1000.0 / df["parallax"]

if "distance_ly" not in df.columns:
    df["distance_ly"] = df["distance_pc"] * 3.26156

# Compute 3D Cartesian coordinates if missing
if "x_ly" not in df.columns:
    dec_rad = np.radians(df["dec"])
    ra_rad = np.radians(df["ra"])
    df["x_ly"] = df["distance_ly"] * np.cos(dec_rad) * np.cos(ra_rad)
    df["y_ly"] = df["distance_ly"] * np.cos(dec_rad) * np.sin(ra_rad)
    df["z_ly"] = df["distance_ly"] * np.sin(dec_rad)

# Absolute Gaia G magnitude
df["absolute_g_mag"] = (
    df["phot_g_mean_mag"]
    - 5 * np.log10(df["distance_pc"])
    + 5
)

def classify_star(row):
    """HR-diagram class; the rule lives in scripts/star_classes.py (shared with Hipparcos)."""
    bp_rp, M_G = row.get("bp_rp"), row.get("absolute_g_mag")
    return classify(None if pd.isna(bp_rp) else float(bp_rp), None if pd.isna(M_G) else float(M_G))

print("Classifying stellar evolutionary stages & spectral classes...")
df["rough_star_type"] = df.apply(classify_star, axis=1)

# Friendly catalog label
df["catalog_label"] = "Gaia DR3 " + df["source_id"].astype(str)

# Landmark names resolved through SIMBAD (see scripts/resolve_star_names.py).
# HIP_NAMES is not used yet: this input has no Hipparcos rows. Once Hipparcos-only
# stars (e.g. alf Cen A/B, Menkent, Dubhe) are merged in, label them with
# df["hip"].astype(str).map(HIP_NAMES).
GAIA_NAMES, HIP_NAMES = load_star_names()
df["star_name"] = df["source_id"].map(GAIA_NAMES).fillna("")

# Sort nearest first
df = df.sort_values("distance_ly")

print(f"Saving catalog to {output_file}...")
df.to_csv(output_file, index=False)
print("Saved successfully!")
print(f"Total stars cataloged: {len(df):,}")
named_count = (df['star_name'] != '').sum()
print(f"Named landmark stars: {named_count}")

print("\nSpectral / Evolutionary Distribution:")
for stype, count in df["rough_star_type"].value_counts().items():
    print(f"  • {stype:20s}: {count:6,} ({count/len(df)*100:4.1f}%)")
